# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 100 # it will paginate after this number
language: 'ko-kr'

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: ''

# Website info
title: go2zo
description: The professional publishing platform
cover: assets/images/blog-cover.jpg
logo: assets/images/blog-icon3.png
logo_dark: assets/images/favicon.png
favicon: assets/images/favicon.png
production_url: https://go2zo.github.io/
source_url: https://github.com/go2zo/go2zo.github.io

# Social info
navigation: True # show the navbar links
subscribers: True # you need to connect an external service for this to work,
# if 'True' the submit button is disabled for now, but you can change that
# by editing `_includes/subscribe-form.html`
twitter: go2zo # replace by your username
facebook: go2zo # replace by your username

# Permalinks
permalink: /blog/:title
# permalink: /author/:author
# permalink: /tag/:tag

# Authors' info in `_data/authors.yml`
# Tags' info in `_data/tags_info.yml`

# gems and other configs
plugins: [jekyll-paginate, jekyll-feed]

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: False
lsi: False
username: go2zo
repo: jekyll-blog
branch: gh-pages
# relative_source: ../jasper2/
# destination: ../jasper2-pages/
production_url:  https://go2zo.github.io/jekyll-blog/
source_url:  https://github.com/go2zo/jekyll-blog/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Default extension for new posts and pages
post_ext: md
page_ext: html

# Default templates for posts and pages
# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft
